<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.github.theestimator</groupId>
    <artifactId>the-estimator</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>The Estimator</name>

    <modules>
        <module>src/domain</module>
        <module>src/frontend</module>
        <module>src/backend</module>
    </modules>

    <profiles>
        <profile>
            <id>dev-local</id>
            <properties>
                <quarkus.profile>dev-local</quarkus.profile>
                <quarkus.container-image.build>false</quarkus.container-image.build>
            </properties>
        </profile>
        <profile>
            <id>dev-minikube</id>
            <properties>
                <quarkus.profile>dev-minikube</quarkus.profile>
                <quarkus.container-image.build>true</quarkus.container-image.build>
            </properties>
        </profile>
    </profiles>
</project>
