apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: estimation
spec:
  tls:
    - hosts:
        - ${INGRESS_HOST}
      secretName: estimation-tls
  rules:
    - host: ${INGRESS_HOST}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
