apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: pythia/pythia-backend
    newName: REGISTRY_PLACEHOLDER/estimation-backend
  - name: pythia/pythia-frontend
    newName: REGISTRY_PLACEHOLDER/estimation-frontend
replicas:
  - name: backend
    count: 2
patches:
  - path: backend-oidc.yaml
    target:
      kind: ConfigMap
      name: backend-config
  - path: ingress-tls.yaml
    target:
      kind: Ingress
      name: estimation
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
